# python assignment - II

#  A.ARAVINDHAN-B.TECH

#     AI&DS

#   25.07.2022


# 1.inheritance

In [2]:
class Parent(object):
    def _protected(self):
        pass

    def __private(self):
        pass

class Child(Parent):
    def foo(self):
        self._protected()   

    def bar(self):
        self.__private()

In [114]:
class Child(Parent):
    def foo(self):
        self._protected()

    def bar(self):
        self._Parent__private()


In [115]:
class Parent(object):
    def _protected(self):
        pass

    def __private(self):
        print("Is it really private?")

class Child(Parent):
    def foo(self):
        self._protected()

    def bar(self):
        self.__private()

c = Child()
c._Parent__private()

Is it really private?


exception handling

In [105]:
print "hello"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("hello")? (2253489653.py, line 1)

In [106]:
a = [1,2,3]
a[4]

IndexError: list index out of range

In [107]:
import notamodule

ModuleNotFoundError: No module named 'notamodule'

In [108]:
D1={'1':"aa", '2':"bb", '3':"cc"}
D1['4']

KeyError: '4'

In [109]:
x=100/0
x

ZeroDivisionError: division by zero

In [110]:
name=input('enter your name')
enter your name^c

SyntaxError: invalid syntax (447927798.py, line 2)

In [111]:
try:
     print("divison")
     print(1 / 0)
except:
     print("an error occurs")
finally:
     print("division done")

divison
an error occurs
division done


In [112]:
try:
    amount = 1999
    if amount < 2999:
          
        raise ValueError("please add money in your account")
    else:
        print("You are eligible")
except ValueError as e:
        print(e)

please add money in your account


3.Regular expression

In [102]:
import re

findall()

In [5]:
txt = "a watermelon as melon"
x = re.findall("a",txt)
x

['a', 'a', 'a']

In [8]:
txt = "a watermelon in melon"
x = re.findall("melon",txt)
print(x)
if(x):
    print("the matching is available")
else:
    print("no match")

['melon', 'melon']
the matching is available


search()

In [15]:
txt = "a watermelon as melon"
x = re.search("\s",txt)
print("the first white-space character is located in position: ",x.start())

the first white-space character is located in position:  1


In [18]:
txt = "a watermelon as melon"
x = re.search("apple",txt)
print(x)

None


split

In [20]:
txt = "a watermelon as melon"
x = re.split("\s",txt)
print(x)

['a', 'watermelon', 'as', 'melon']


maxsplit()

In [24]:
txt = "a watermelon as melon"
x = re.split("\s",txt,2)
print(x)

['a', 'watermelon', 'as melon']


sub()

In [25]:
txt = "a watermelon as melon"
x = re.sub("\s","-",txt)
print(x)

a-watermelon-as-melon


In [27]:
txt = "a watermelon as melon"
x = re.sub("\s","-",txt,2)
print(x)

a-watermelon-as melon


4.aggregate functions (numpy)

In [28]:
import numpy as np

In [33]:
l = np.random.randint(2,20,5)
print(l)

[19  8 19 16 11]


one-dimensional array

In [36]:
l = np.array([50,100,3000,25,0])
e=np.min(l)
f=np.max(l)
print(e)
print(f)

0
3000


multi-dimensional array

In [37]:
l = np.random.randint(0,20,(3,3))
print(l)

[[ 2  5 16]
 [ 1  8 12]
 [17 11  9]]


In [38]:
e = l.sum()
f = l.max()
g = l.min()
print(e)
print(f)
print(g)

81
17
1


product()

In [41]:
l = np.prod([[1,4],
             [7,10]])
print(l)

280


mean()

In [42]:
a = np.array([[1,4],[3,4]])
np.mean(a)

3.0

var()

In [43]:
a = np.array([[1,2],[3,4]])
np.var(a)

1.25

median()

In [44]:
a = np.array([[1,2],[3,4]])
np.median(a)

2.5

In [47]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9])
print(np.percentile(a,b))

[1.15 1.18 1.21 1.24 1.27]


comparisons,masks and boolean array

In [48]:
import numpy as np
import pandas as pd

In [50]:
x = np.array([1, 2, 3, 4, 5])

In [55]:
x < 2

array([ True, False, False, False, False])

In [53]:
x > 4

array([False, False, False, False,  True])

In [56]:
x >= 4

array([False, False, False,  True,  True])

In [57]:
x <= 3

array([ True,  True,  True, False, False])

In [58]:
x!= 2

array([ True, False,  True,  True,  True])

In [59]:
x==2

array([False,  True, False, False, False])

In [61]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [63]:
y=np.random.RandomState(0)
x = y.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [64]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [65]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [67]:
np.count_nonzero(x < 3)

2

In [69]:
np.sum(x<3)

2

In [71]:
np.sum(x < 3, axis=1)

array([1, 0, 1])

In [73]:
np.any(x>2)

True

In [74]:
np.all(x < 10)

True

In [75]:
np.all(x == 6)

False

In [76]:
np.all(x < 8, axis=1)

array([ True, False,  True])

boolean operators

In [86]:
rainfall = pd.read_csv('C:\Users\Srimathi\OneDrive\Desktop\New folder(2)\archive\weatherAUS.csv')['Rainfall'].values
print(rainfall)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (873305947.py, line 1)

In [88]:
bool(20), bool(0)

(True, False)

In [90]:
bool(20 and 0)

False

In [91]:
bool(20 or 0)

True

In [93]:
bin(20)

'0b10100'

In [94]:
bin(42 and 30)

'0b11110'

In [96]:
bin(4 and 3)

'0b11'

datatype should be mentioned to get similar output

In [98]:
A = np.array([1, 0, 1, 0, 1, 0])
B = np.array([1, 1, 1, 0, 1, 1])
A | B

array([1, 1, 1, 0, 1, 1], dtype=int32)

In [99]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [101]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])